export type AnchorLifecycleState = ...
export type RangeLifecycleState = ...
export type GlobalStructuralState = ...

export interface L5Input {
  anchorState: AnchorLifecycleState
  rangeState: RangeLifecycleState
}
